
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.12.5
CC = ../../afl-cov/afl-clang-fast
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng16  -fexcess-precision=fast
LDFLAGS =  ./lib/libimagequant.a -lpng16 -lz -lz -lm
SOLIBSUFFIX = so
STATICLIBDEPS = ./lib/libimagequant.h ./lib/libimagequant.a
LIQSRCDIR = ./lib
LIQCONFIGUREFLAGS = '--quiet' 

