.TH PNGCHUNKDESC 1 "Tue, 31 Jul 2007 17:55:51 \-0300"
.SH NAME
pngchunkdesc \- decode information embedded into a PNG chunk name
.SH SYNOPSIS
.B pngchunkdesc
.SH DESCRIPTION
PNG files are based around a series of chunks, which embody the information stored in the image file. These chunks have four character ASCII names, where the case of each letter stores additional information.
.PP
This program decodes the case information in the chunk names, and displays it. The program reads chunk names from stdin, and write chunk descriptions to stdout.
.SH SEE ALSO
.BR pngchunks (1),
.BR pngcp (1),
.BR pnginfo (1).
.SH AUTHOR
pngchunkdesc was written by Michael Still <mikal@stillhq.com>.
.PP
This manual page was written by Nelson A. de Oliveira <naoliv@debian.org>,
for the Debian project (but may be used by others).
