name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        sudo apt install meson ninja-build gcovr clang-tools libubsan1
        CC=clang CXX=clang++ meson -Ddev_build=true -Db_sanitize=address,undefined -Db_lundef=false clang_build
        ninja -C clang_build test
        ninja -C clang_build scan-build # this uses gcc due to a bug: https://github.com/mesonbuild/meson/issues/5716
        CC=gcc CXX=g++ meson -Ddev_build=true -Db_sanitize=address,undefined -Db_coverage=true gcc_build
        cd gcc_build
        ninja
        meson test info -v
        ninja test
        ninja coverage-text
        cat meson-logs/coverage.txt
        cd ..
        #bash <(curl -s https://codecov.io/bash)
        
        wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=randy408%2Flibspng" -O coverity_tool.tgz
        mkdir coverity_tool
        tar -xvzf coverity_tool.tgz -C coverity_tool --strip-components=1
        ninja -C gcc_build clean
        ./coverity_tool/bin/cov-build --dir cov-int ninja -C gcc_build
        tar czvf spng.tgz cov-int
        curl --form token=$COVERITY_TOKEN --form file=@spng.tgz --form version="master" --form description="libspng" https://scan.coverity.com/builds?project=randy408%2Flibspng
        rm spng.tgz
        rm -r cov-int
